FROM eclipse-temurin:11.0.13_8-jre-focal

WORKDIR app

ARG DEPENDENCY=build/dependency
COPY ${DEPENDENCY}/dependencies/ ./
COPY ${DEPENDENCY}/spring-boot-loader/ ./
COPY ${DEPENDENCY}/snapshot-dependencies/ ./
COPY ${DEPENDENCY}/application/ ./

ENV JELU_DATABASE_PATH="/database/"
ENV JELU_FILES_DIR="/files/"
ENV LC_ALL=en_US.UTF-8
ENV JELU_METADATA_CALIBRE_PATH="/usr/bin/fetch-ebook-metadata"

RUN apt-get update && apt-get install --no-install-recommends --yes calibre \
  && curl https://www.mobileread.com/forums/attachment.php\?attachmentid\=182200\&d\=1641360812 > goodreads.zip \
    && calibre-customize --add-plugin goodreads.zip \
    && rm goodreads.zip

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher", "--spring.config.additional-location=optional:file:/config/"]
EXPOSE 11111
