export interface Author {
  id?: string,
  creationDate?: string,
  name: string,
  modificationDate?: string,
  biography?: string,
  dateOfBirth?: Date,
  dateOfDeath?: Date,
  image?: string,
  notes?: string,
  officialPage?: string,
  wikipediaPage?: string,
  goodreadsPage?: string,
  twitterPage?: string,
  facebookPage?: string,
  instagramPage?: string,
}
